name: Restringir acceso por IP a archivo inicial.rsc

on:
  pull_request:
    paths:
      - 'bloqueo_mintic/inicial.rsc'  # Ruta al archivo inicial.rsc que quieres proteger

jobs:
  check-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar IP permitida
        id: check_ip
        run: |
          permitted_ips=($(cat allowed_ips.txt))  # Leer IPs permitidas desde allowed_ips.txt
          client_ip=$(curl https://api.ipify.org)
          if [[ " ${permitted_ips[@]} " =~ " ${client_ip} " ]]; then
            echo "::set-output name=allowed::true"
          else
            echo "::set-output name=allowed::false"
          fi

      - name: Descargar inicial.rsc si la IP está permitida
        if: steps.check_ip.outputs.allowed == 'true'
        run: |
          curl -O https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/bloqueo_mintic/inicial.rsc

      - name: Denegar acceso si la IP no está permitida
        if: steps.check_ip.outputs.allowed != 'true'
        run: echo "Acceso denegado. Tu IP no está permitida para descargar inicial.rsc."
