name: Procesar URLs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  process_urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run URL processing script
        run: python main.py

      - name: Upload urls_con_codigos artifact
        uses: actions/upload-artifact@v4
        with:
          name: urls_con_codigos
          path: urls_con_codigos.txt

      - name: Upload urls_divididas artifact
        uses: actions/upload-artifact@v4
        with:
          name: urls_divididas
          path: urls_divididas.txt

      - name: Upload updated listado_urls.rsc
        uses: actions/upload-artifact@v4
        with:
          name: listado_urls
          path: listado_urls.rsc
