name: Generar archivos de configuración

on:
  push:
    branches:
      - main

jobs:
  generar-archivos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Ejecutar script Python
        run: python extraer_dominios.py

      - name: Subir archivos como artefactos
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Archivos de configuración
          path: |
            bloqueo_mintic/listado_urls.rsc
            bloqueo_mintic/acces.rsc
            bloqueo_mintic/address_list.rsc
